version: '3.8'
services:
  api:
    # image: ii-platform-api
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'

  postgres:
    image: postgres:latest
    ports:
      - '${DB_PORT_PREFIX}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
