export const USERS = [
  {
    email: 'email1@gmail.com',
    firstName: 'Сергей',
    lastName: 'Рахвалов',
    nickname: 'serega',
    birthDate: '1990-11-05',
    residenceCountry: 'Казахстан',
    residenceCity: 'Павло',
    occupation: 'рэппер',
    workCompany: 'Музыка36',
    educationalInstitution: 'НУ',
    bio: 'Чат сам себя не напишет',
    telegramNickname: 'seregaaaaa',
    linkedinLink: 'https://www.linkedin.com/in/sultan-mustafin-44382b1a6/',
    description:
      'Описание Сергея и еще длинеее строка для заполнения пространства',
    role: 1,
    password: '$2a$10$Tx1B/3h2.26ppwkPARIywuOqHLAP8ZsHYie4vtHJAGInYFSZ.9UTG',
    avatarUrl: 'https://i.pravatar.cc/300',
  },
  {
    email: 'email2@gmail.com',
    firstName: 'Аня',
    lastName: 'Пирожкова',
    nickname: 'serega',
    birthDate: '1990-11-05',
    residenceCountry: 'Казахстан',
    residenceCity: 'Павло',
    occupation: 'рэппер',
    workCompany: 'Музыка36',
    educationalInstitution: 'НУ',
    bio: 'Чат сам себя не напишет',
    telegramNickname: 'seregaaaaa',
    linkedinLink: 'https://www.linkedin.com/in/sultan-mustafin-44382b1a6/',
    description:
      'Описание Сергея и еще длинеее строка для заполнения пространства',
    role: 1,
    password: '$2a$10$Tx1B/3h2.26ppwkPARIywuOqHLAP8ZsHYie4vtHJAGInYFSZ.9UTG',
    avatarUrl: 'https://i.pravatar.cc/300',
  },
  {
    email: 'email3@gmail.com',
    firstName: 'Генри',
    lastName: 'Винсентович',
    nickname: 'serega',
    birthDate: '1990-11-05',
    residenceCountry: 'Казахстан',
    residenceCity: 'Павло',
    occupation: 'рэппер',
    workCompany: 'Музыка36',
    educationalInstitution: 'НУ',
    bio: 'Чат сам себя не напишет',
    telegramNickname: 'seregaaaaa',
    linkedinLink: 'https://www.linkedin.com/in/sultan-mustafin-44382b1a6/',
    description:
      'Описание Сергея и еще длинеее строка для заполнения пространства',
    role: 1,
    password: '$2a$10$Tx1B/3h2.26ppwkPARIywuOqHLAP8ZsHYie4vtHJAGInYFSZ.9UTG',
    avatarUrl: 'https://i.pravatar.cc/300',
  },
  {
    email: 'email4@gmail.com',
    firstName: 'Аяжан',
    lastName: 'Даутова',
    nickname: 'serega',
    birthDate: '1990-11-05',
    residenceCountry: 'Казахстан',
    residenceCity: 'Павло',
    occupation: 'рэппер',
    workCompany: 'Музыка36',
    educationalInstitution: 'НУ',
    bio: 'Чат сам себя не напишет',
    telegramNickname: 'seregaaaaa',
    linkedinLink: 'https://www.linkedin.com/in/sultan-mustafin-44382b1a6/',
    description:
      'Описание Сергея и еще длинеее строка для заполнения пространства',
    role: 1,
    password: '$2a$10$Tx1B/3h2.26ppwkPARIywuOqHLAP8ZsHYie4vtHJAGInYFSZ.9UTG',
    avatarUrl: 'https://i.pravatar.cc/300',
  },
];
