export const USERS = [
  {
    firstName: 'Jack',
    lastName: 'Brown',
    email: 'email1@gmail.com',
    nickname: 'jack',
    birthDate: '1990-11-05',
    occupation: 'player',
    residenceCountry: 'Kazakhstan',
    residenceCity: 'Pavlodar',
    bio: 'This is my bio',
    avatarUrl: 'https://i.pravatar.cc/300',
    role: 1,
    password: '$2a$10$Tx1B/3h2.26ppwkPARIywuOqHLAP8ZsHYie4vtHJAGInYFSZ.9UTG',
  },
  {
    firstName: 'Jack',
    lastName: 'Brown',
    email: 'email1@gmail.com',
    nickname: 'jack',
    birthDate: '1990-11-05',
    occupation: 'player',
    residenceCountry: 'Kazakhstan',
    residenceCity: 'Pavlodar',
    bio: 'This is my bio',
    avatarUrl: 'https://i.pravatar.cc/300',
    role: 1,
    password: '$2a$10$Tx1B/3h2.26ppwkPARIywuOqHLAP8ZsHYie4vtHJAGInYFSZ.9UTG',
  },
];
